apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag-pipeline.fullname" . }}
  labels:
    {{- include "rag-pipeline.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  MOCK_MODE: {{ .Values.env.MOCK_MODE | quote }}
